site_name: Лабораторные работы

theme:
  name: material
  language: ru

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Список работ: labs/index.md
      - Лабораторная работа №1: labs/lab1.md
      - Лабораторная работа №2: labs/lab2.md
      - Лабораторная работа №3: labs/lab3.md

markdown_extensions:
  - fenced_code
  - tables
